### ISSUE TITLE
support HUP

### ISSUE THREAD

**Issue by borats** [pseidemann/finish#1]
The idea is once a `SIGHUP` signal is received by the binary under `finish`'s control, it will reload its configuration whilst keeping the `Add()`'ed server intact (no disruption to the client connection). This also means instrumenting a configurable knobs that `finish` can use; either via declarative `yaml` like construct or plain 'ol JSON..

**Comment by borats** [comment]
@pseidemann for the first bit you nailed it:
```
fin := &finish.Finisher{Signals: append(finish.DefaultSignals, syscall.SIGHUP)}
fin.Add(srv)
...
fin.Wait()
```
However, what I am referring to is the ability for fin to recognise `SIGHUP` *and* be able to reload configurable knobs upon receiving it.

E.g.:
```
fin := finish.NewFinisher(cfg) // cfg is some type of config where we define what we do with signal dispositions / how finisher behaves upon receiving it
fin.Add(srv)
fin.Wait()
```

If I send `HUP` to the above process, it will reload its world view of `cfg` but keeps the `Add(srv)`ed server intact and will not close/shutdown any active in-flight client connections' state that are bound to the server.

Makes sense?

**Comment by pseidemann** [comment]
I would suggest doing the following but that would not be directly related to finish:

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"github.com/pseidemann/finish"
)

type config struct {
	sync.RWMutex
	myValue string
}

func (c *config) load() {
	c.Lock()
	defer c.Unlock()
	// TODO: load config from file and set c.myValue
	c.myValue = time.Now().String() // set some value which changes
}

func (c *config) getMyValue() string {
	c.RLock()
	defer c.RUnlock()
	return c.myValue
}

func (c *config) waitForReload() {
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGHUP)
	for {
		<-sig
		log.Println("reloading config")
		c.load()
	}
}

func main() {
	cfg := &config{}
	cfg.load()
	go cfg.waitForReload()

	http.HandleFunc("/hello", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, cfg.getMyValue())
	})

	srv := &http.Server{Addr: "localhost:8080"}

	fin := finish.New()
	fin.Add(srv)

	go func() {
		err := srv.ListenAndServe()
		if err != http.ErrServerClosed {
			log.Fatal(err)
		}
	}()

	fin.Wait()
}
```

test:
```sh
$ curl localhost:8080/hello
2018-05-29 16:30:23.143391552 +0200 CEST m=+0.001903202
# it stays the same:
$ curl localhost:8080/hello
2018-05-29 16:30:23.143391552 +0200 CEST m=+0.001903202
# until SIGHUP:
$ kill -SIGHUP <pid>
$ curl localhost:8080/hello
2018-05-29 16:31:04.77121378 +0200 CEST m=+41.628544354
```

**Comment by borats** [comment]
Ahh that's ok. i was thinking in the spirit of a UNIX-based process orchestrators/managers, but probably suffice to say that `finish` doesn't intend to be one; nor that it is designed with the hindsight in mind. good day to you.
