### ISSUE TITLE
CTRL + Z ?

### ISSUE THREAD

**Issue by AlexanderWM** [pseidemann/finish#2]
Hello! What about CTRL + Z in console (SIGSTOP signal)?

**Comment by pseidemann** [comment]
Hi @AlexanderWM,

it seems SIGSTOP is not catchable by an application, see:
https://www.gnu.org/software/libc/manual/html_node/Job-Control-Signals.html

However, you can configure any signal you want with passing the `Signals` member when constructing `finish.Finisher`.

For example, if you want it to handle SIGHUP besides the default signals SIGINT and SIGTERM, do the following:

```go
fin := &finish.Finisher{Signals: append(finish.DefaultSignals, syscall.SIGHUP)}
// ...
```
