### ISSUE TITLE
multi port example?

### ISSUE THREAD

**Issue by miRemid** [pseidemann/finish#3]
Hello! i find this lib from this [link](https://gist.github.com/rivo/f96ad8710b54a49180a314ec4d68dbfb)

i want to use it in a multi port project, can you provide an example of it? thanks :D

**Comment by pseidemann** [comment]
hi,

in the "full example" there are two servers/ports:
https://github.com/pseidemann/finish#full-example

- you create a handler for each server (https://pkg.go.dev/net/http#Handler), in the example I used httprouter, but you could also use e.g. go's own muxer https://pkg.go.dev/net/http#ServeMux (there is an example how to use it at the Handle() function doc)
- you create two servers
  `srv1 := &http.Server{Addr: "localhost:8000", Handler: handler1}`
  `srv2 := &http.Server{Addr: "localhost:9000", Handler: handler2}`
- you add both servers to finish
  `fin.Add(srv1)`
  `fin.Add(srv2)`

let me know if this helps.

**Comment by miRemid** [comment]
sorry, i just regard the full example as the summary of the previous😂, thanks for your reply, close the issue

**Comment by pseidemann** [comment]
@miRemid sorry I don't follow. did this help?

**Comment by miRemid** [comment]
yes, thanks for your help
